### ISSUE TITLE
KeyError: 'Y' with mnist_all

### ISSUE THREAD

**Issue by GPhMorin** [hyzhang98/AnchorGAE-torch#1]
When running the code:

```(venv) user@ubuntu:~/AnchorGAE-torch$ python3 Main.py --datasetName mnist_all
Traceback (most recent call last):
  File "/home/user/AnchorGAE-torch/Main.py", line 56, in <module>
    main(args)
  File "/home/user/AnchorGAE-torch/Main.py", line 14, in main
    [data, labels] = loader.load_data(args.datasetName)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/AnchorGAE-torch/data_loader.py", line 23, in load_data
    labels = data['Y']
             ~~~~^^^^^
KeyError: 'Y'
```

**Comment by hyzhang98** [comment]
Hi, this exception is raised by the missing dataset files. You can download Fashion-MNIST from https://github.com/zalandoresearch/fashion-mnist and resave it as ".mat" (matlab data file) using scipy.io.

**Comment by GPhMorin** [comment]
Thank you!
