### ISSUE TITLE
fashionMNIST_full is missing

### ISSUE THREAD

**Issue by GPhMorin** [hyzhang98/AnchorGAE-torch#2]
```
(venv) user@ubuntu:~/AnchorGAE-torch$ python3 Main.py --datasetName fashionMNIST_full
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/fashionMNIST_full.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/AnchorGAE-torch/Main.py", line 56, in <module>
    main(args)
  File "/home/user/AnchorGAE-torch/Main.py", line 14, in main
    [data, labels] = loader.load_data(args.datasetName)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/AnchorGAE-torch/data_loader.py", line 15, in load_data
    data = scio.loadmat(path)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/user/venv/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/fashionMNIST_full.mat'
```

**Comment by GPhMorin** [comment]
Answered in https://github.com/hyzhang98/AnchorGAE-torch/issues/1.
